// actionTypes.js
export const GET_USER_LOCATION_REQUEST = "GET_USER_LOCATION_REQUEST";
export const GET_USER_LOCATION_SUCCESS = "GET_USER_LOCATION_SUCCESS";
export const GET_USER_LOCATION_FAILURE = "GET_USER_LOCATION_FAILURE";
